
package com.demo.ws.cxf.helloservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-31T15:29:42.065-08:00
 * Generated source version: 2.7.8
 * 
 */
public final class HelloPortType_HelloPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.demo.com/ws/cxf/HelloService", "HelloService");

    private HelloPortType_HelloPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
        HelloPortType port = ss.getHelloPort();  
        
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_firstName = "World";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_firstName);
        System.out.println("sayHello.result=" + _sayHello__return);


        }

        System.exit(0);
    }

}
