
package com.demo.ws.cxf.helloservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-31T15:36:42.129-08:00
 * Generated source version: 2.7.8
 * 
 */
 
public class HelloPortType_HelloPort_Server{

    protected HelloPortType_HelloPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new HelloPortTypeImpl();
        String address = "http://localhost:8080/SayHello/";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new HelloPortType_HelloPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
