package com.demo.ws.cxf.helloservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * WSDL File for HelloService
 *
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-31T15:29:38.426-08:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "HelloService", 
                  wsdlLocation = "DemoHello.wsdl",
                  targetNamespace = "http://www.demo.com/ws/cxf/HelloService") 
public class HelloService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.demo.com/ws/cxf/HelloService", "HelloService");
    public final static QName HelloPort = new QName("http://www.demo.com/ws/cxf/HelloService", "HelloPort");
    static {
        URL url = HelloService.class.getResource("DemoHello.wsdl");
        if (url == null) {
            url = HelloService.class.getClassLoader().getResource("DemoHello.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(HelloService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "DemoHello.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "HelloPort")
    public HelloPortType getHelloPort() {
        return super.getPort(HelloPort, HelloPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloPortType
     */
    @WebEndpoint(name = "HelloPort")
    public HelloPortType getHelloPort(WebServiceFeature... features) {
        return super.getPort(HelloPort, HelloPortType.class, features);
    }

}
